### PR TITLE
Fixes from a coverity scan

### PR DESCRIPTION
**Pull request by sbird**
Mostly these are fixes to resource allocation in error paths, and a couple of extra data checks. Should not affect anything in normal usage.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Travis is red. Looks like the python binding is/was broken?

**Comment by sbird** [comment]
hmm. I think the mkdir whose return is now checked always failed!

**Comment by sbird** [comment]
Certainly it does not actually recursively make a subdirectory, because it calls mkdir with the full subdirectory name each time.

**Comment by sbird** [comment]
Oh, no, I see. Null terminated strings!

**Comment by rainwoodman** [comment]
If I recall correctly, if the directory already exist mkdir shall fail, but we shall ignore the execption in mkdir_r if the directory is already there -- all we were to do is to ensure the directory exist.

**Comment by sbird** [comment]
Good point, will fix that.

**Comment by sbird** [comment]
How's that?

**Comment by rainwoodman** [comment]
But why did the "" happen?

**Comment by rainwoodman** [comment]
I'll merge and see.

**Comment by sbird** [comment]
mkdir("") fails with ENOENT - your fix is better though.

**Comment by rainwoodman** [comment]
Can we add the coverity scan to travis?

**Comment by sbird** [comment]
I think so - do you want me to set it up? There are limits on how often you are supposed to run it, so the recommended way is to create a special branch and periodically merge it with master.

**Comment by rainwoodman** [comment]
I'll take care of it then. It is tricky.

**Comment by sbird** [comment]
Take a look at https://github.com/sbird/GadgetReader/blob/coverity_scan/.travis.yml for an example of how to configure travis

**Comment by rainwoodman** [comment]
Yours require sudo -- and that command doesn't seem to be useful at all..

**Comment by sbird** [comment]
The S-GenIC requires sudo for unrelated reasons, but GadgetReader doesn't.

**Comment by rainwoodman** [comment]
Sorry I meant the openssl commandline.

**Comment by sbird** [comment]
hm, point. I copied that from coverity's default without thinking about it...let me know if not actually needed.

**Comment by rainwoodman** [comment]
No It doesn't seem to be needed now. I am guessing at one point they loss their SSL certificate??
I also noticed you use two .travis.yaml -- which may cause merge issues down the road. Take a look at
https://github.com/travis-ci/travis-ci/issues/1975

**Pull request merged**
